# Vagrant configuration version 2
Vagrant.configure("2") do |config|

 # Use a relatively lightweight Ubuntu box
 config.vm.box = "bento/ubuntu-16.04"

 # Allow access to the VM
 config.vm.network "private_network", ip: "10.0.0.2"

 # If using virtualbox, get a GUI
 config.vm.provider "virtualbox" do |vb|
   vb.gui = true
 end
 
 # Install python
 # config.vm.provision "shell", inline: "apt install --yes python3-pip"

 # Run ansible playbook
 config.vm.provision "ansible" do |ansible|
   ansible.verbose = "vv"
   ansible.playbook = "test.yml"
 end
end

